export const HADITH_INDEX_REQUEST = 'HADITH_INDEX_REQUEST';
export const HADITH_INDEX_SUCCESS = 'HADITH_INDEX_SUCCESS';
export const HADITH_INDEX_FAIL = 'HADITH_INDEX_FAIL';

export const HADITH_BOOK_INDEX_REQUEST = 'HADITH_BOOK_INDEX_REQUEST';
export const HADITH_BOOK_INDEX_SUCCESS = 'HADITH_BOOK_INDEX_SUCCESS';
export const HADITH_BOOK_INDEX_FAIL = 'HADITH_BOOK_INDEX_FAIL';

export const HADITH_BOOK_INDEX_BY_CHAPTER_AND_RANGE_REQUEST =
  'HADITH_BOOK_INDEX_BY_CHAPTER_AND_RANGE_REQUEST';
export const HADITH_BOOK_INDEX_BY_CHAPTER_AND_RANGE_SUCCESS =
  'HADITH_BOOK_INDEX_BY_CHAPTER_AND_RANGE_SUCCESS';
export const HADITH_BOOK_INDEX_BY_CHAPTER_AND_RANGE_FAIL =
  'HADITH_BOOK_INDEX_BY_CHAPTER_AND_RANGE_FAIL';

export const HADITH_BY_BOOK_KEY_REQUEST = 'HADITH_BY_BOOK_KEY_REQUEST';
export const HADITH_BY_BOOK_KEY_SUCCESS = 'HADITH_BY_BOOK_KEY_SUCCESS';
export const HADITH_BY_BOOK_KEY_FAIL = 'HADITH_BY_BOOK_KEY_FAIL';
