export const QURAN_INDEX_REQUEST = 'QURAN_INDEX_REQUEST';
export const QURAN_INDEX_SUCCESS = 'QURAN_INDEX_SUCCESS';
export const QURAN_INDEX_FAIL = 'QURAN_INDEX_FAIL';

export const QURAN_AYAT_REQUEST = 'QURAN_AYAT_REQUEST';
export const QURAN_AYAT_SUCCESS = 'QURAN_AYAT_SUCCESS';
export const QURAN_AYAT_FAIL = 'QURAN_AYAT_FAIL';
